database:
  path: database/spotify.duckdb

source:
  spotify_json_path: data/source/dataset

schemas:
  bronze: bronze
  silver: silver
  gold: gold
  pipeline: pipeline

sql:
  path: sql

pipeline:
  name: spotify_music_pipeline
